DROP TABLE IF EXISTS BRAND;
  
CREATE TABLE BRAND (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  BRAND_NAME VARCHAR(250) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS SELLER;
  
CREATE TABLE SELLER (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  SELLER_NAME VARCHAR(250) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL
);


DROP TABLE IF EXISTS SHIRT;
  
CREATE TABLE SHIRT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  BRAND_ID INT,
  SELLER_ID INT,
  DESCRIPTION VARCHAR(250) NOT NULL,
  TYPE VARCHAR(250) DEFAULT NULL,
  PRICE INT,
  COLOR VARCHAR(250) DEFAULT NULL,
  SIZE INT,
  SKU INT,
  CONSTRAINT shirt_brand
  FOREIGN KEY (BRAND_ID)
  REFERENCES BRAND (ID)
);



DROP TABLE IF EXISTS PANT;
  
CREATE TABLE PANT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  BRAND_ID INT,
  SELLER_ID INT,
  DESCRIPTION VARCHAR(250) NOT NULL,
  TYPE VARCHAR(250) DEFAULT NULL,
  PRICE INT,
  COLOR VARCHAR(250) DEFAULT NULL,
  SIZE INT,
  SKU INT,
  CONSTRAINT pant_brand
  FOREIGN KEY (BRAND_ID)
  REFERENCES BRAND (ID)
);

DROP TABLE IF EXISTS SOCK;
  
CREATE TABLE SOCK (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  BRAND_ID INT,
  SELLER_ID INT,
  DESCRIPTION VARCHAR(250) NOT NULL,
  TYPE VARCHAR(250) DEFAULT NULL,
  PRICE INT,
  COLOR VARCHAR(250) DEFAULT NULL,
  SIZE INT,
  SKU INT,
  CONSTRAINT sock_brand
  FOREIGN KEY (BRAND_ID)
  REFERENCES BRAND (ID)
);


DROP TABLE IF EXISTS CAP;
  
CREATE TABLE CAP (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  BRAND_ID INT,
  SELLER_ID INT,
  DESCRIPTION VARCHAR(250) NOT NULL,
  TYPE VARCHAR(250) DEFAULT NULL,
  PRICE INT,
  COLOR VARCHAR(250) DEFAULT NULL,
  SIZE INT,
  SKU INT,
  CONSTRAINT cap_brand
  FOREIGN KEY (BRAND_ID)
  REFERENCES BRAND (ID)
);


